/*
 * Todo
 *
 * Todo API specification
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

type Error struct {

	// Error code
	Code string `json:"code,omitempty"`

	// Error message
	Message string `json:"message"`
}
