/*
 * Todo
 *
 * Todo API specification
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type TodoList struct {

	// List of todo items
	Items []Todo `json:"items"`

	// Total number of items
	Total float32 `json:"total"`
}
