/*
 * Todo
 *
 * Todo API specification
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Todo struct {

	// Id
	Id string `json:"id,omitempty"`

	// Title
	Title string `json:"title"`

	// Category
	Category string `json:"category"`

	// Content
	Content string `json:"content,omitempty"`
}
