/*
 * Todo
 *
 * Todo API specification
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"example/backend/todo"
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

// NewRouter returns a new router.
func AddRoutes(router *gin.Engine) {
	for _, route := range routes {
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusOK, "Hello World!")
}

var routes = Routes{
	{
		"TodoControllerDelete",
		http.MethodDelete,
		"/todos/:id",
		todo.Del,
	},

	{
		"TodoControllerGet",
		http.MethodGet,
		"/todos/:id",
		todo.Get,
	},

	{
		"TodoControllerGetList",
		http.MethodGet,
		"/todos",
		todo.GetList,
	},

	{
		"TodoControllerPost",
		http.MethodPost,
		"/todos",
		todo.Post,
	},

	{
		"TodoControllerUpdate",
		http.MethodPut,
		"/todos/:id",
		todo.Put,
	},
}
