// Code generated by ent, DO NOT EDIT.

package ent

import (
	"example/backend/ent/schema"
	"example/backend/ent/todo"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	todoFields := schema.Todo{}.Fields()
	_ = todoFields
	// todoDescTitle is the schema descriptor for title field.
	todoDescTitle := todoFields[0].Descriptor()
	// todo.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	todo.TitleValidator = todoDescTitle.Validators[0].(func(string) error)
	// todoDescCategory is the schema descriptor for category field.
	todoDescCategory := todoFields[1].Descriptor()
	// todo.CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	todo.CategoryValidator = todoDescCategory.Validators[0].(func(string) error)
}
